### ISSUE TITLE
java.lang.IllegalStateException when Burpsuite Collaborator is disabled

### ISSUE THREAD

**Issue by tgsyn** [nccgroup/freddy#11]
Hi,

The extension crashes with `java.lang.IllegalStateException` when Burp Collaborator is explicitly disabled in the Project options ("Don't use Burp Collaborator" radio box) during an active scan.

```
java.lang.IllegalStateException: Burp Collaborator is disabled in the Project options
	at burp.uvf.a(Unknown Source)
	at burp.uvf.generatePayload(Unknown Source)
	at burp.zv.generatePayload(Unknown Source)
	at nb.freddy.modules.FreddyModuleBase.doActiveScan(FreddyModuleBase.java:871)
	at nb.freddy.Freddy.doActiveScan(Freddy.java:386)
	at burp.r5d.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

I've put together a monkey patch for this issue (i.e. it's too sketchy for a PR): https://github.com/nccgroup/freddy/compare/master...tgsyn:no-burpcollab

Freddy version 2.2.2
BurpSuite version 1.7.37

**Comment by vdbaan** [comment]
Hi,

thank you for reporting this issue. I will look at your patch, incorporate it and will let you know when it has been fixed.

**Comment by vdbaan** [comment]
The code now contains a specific check to see if the Collaborator is enable and will not continue if it is not.
