### ISSUE TITLE
Payloads not taking private collaborator server settings

### ISSUE THREAD

**Issue by Hipapheralkus** [nccgroup/freddy#5]
Hi,
In Logger++, I noticed that burpcollaborator.net is being used, for example in payload:
![image](https://user-images.githubusercontent.com/4717664/48137294-0ae29180-e2a2-11e8-9121-5c514ffa2ca6.png)
However, I have Burp configured with Private Collaborator server location (true, only by IP address, whereas you use domain). The health check of the Collaborator instance is successful. 
Also, this issue is shown in Alerts, because the official collaborator instance is not reachable from the environment I test, showing:
![image](https://user-images.githubusercontent.com/4717664/48137423-56953b00-e2a2-11e8-8d55-61981411fb09.png)

Could you please have a look and uphold the Private collaborator server deployment in Freddy payloads? Thanks:)

**Comment by vdbaan** [comment]
Thank you for reporting this. I will look into it and fix it.

**Comment by Hipapheralkus** [comment]
thanks, FYI, I was using version 2.0 -> which is to my knowledge the last one on Portswigger repo. When I updated to 2.1.1 and ran the active scan, the few payloads I noticed were containing the correct IP address of my Collaborator server. Hence it may be that this issue was already addressed in more recent versions.

**Comment by Hipapheralkus** [comment]
Actually, I'm still seeing them for the newest version of the Extension... An example:
![image](https://user-images.githubusercontent.com/4717664/49218625-9bac1900-f3d9-11e8-8563-bd778b05bbe8.png)

**Comment by vdbaan** [comment]
Thank you for reporting this. I will look into this and do my best to correct it.

**Comment by vdbaan** [comment]
I have looked into it and noticed that the code gets the server location through IBurpCollaboratorClientContext which is a burp interface.
I have notified Burp about this and asked them to look into it.

**Comment by Hipapheralkus** [comment]
Thanks :) isn't it possible that only some payloads are using the proper collaborator settings, while some payloads have it hardcoded?

**Comment by vdbaan** [comment]
Upon advice from Burp I now check the collaborator settings just before using and thus will detect if you have changed your settings.
