### ISSUE TITLE
NullPointer during startup

### ISSUE THREAD

**Issue by fenceposterror** [nccgroup/freddy#9]
Hi, when starting Burp and the extension was already in the list of extensions to be started, I get a 

```
java.lang.NullPointerException
        at nb.freddy.FreddyCollaboratorThread.run(FreddyCollaboratorThread.java:68)
```

It's the most current release (2.2.1) and Burp 2.0.17.

**Comment by vdbaan** [comment]
Thank you for the notification, I will try to address this as soon as possible.

**Comment by vdbaan** [comment]
Found the issue, will be fixed in next release.
